### ISSUE TITLE
All boxes are 77 col wide

### ISSUE THREAD

**Issue by Whyglobaleyes** [Gulzt/commentBanner#4]
`****************************************************************************
*                                   that                                   *
****************************************************************************`

> ****************************************************************************
> *                                   that                                   *
> ****************************************************************************

Hi,
Newbie here, usual apologies. 
So I'm experimenting with commentBanner - looks great! Besides prettifying bash scripts I hope to use it to create very simple flow diagrams, will save me a HUGE amount of effort to do them right in sublimetext.
Weirdly all my boxes appear as above (format is getting messed up, will try to post an image), looks like it's creating full screen banners instead of creating a box around the selected text.
Can you tell me what I'm doing wrong or how to fix it please. Many thanks in advance.
BW
y(G)ii 

![image](https://user-images.githubusercontent.com/34477666/37823228-cc179e9e-2e80-11e8-83fb-ac460a24d9f1.png)

**Comment by paulvanvulpen** [comment]
Hi, thank you for your message. The result you see is intended use. If you like to use the banners in a different way you are free to fork, or make a manual chance on your system.

If you have the sublime plugin PackageResourceViewer installed, you'll have an easy way to navigate to the source file of my plugin.

Look for commentbanner.py and check line 15. Here you see I hardcoded the 77. You can change it to fit your needs. I hope that helps.

**Comment by LynnHo** [comment]
@Gulzt Is it possible to make the 'width' configurable in a .sublime-setting file. It will also be preferable that we can use other symbols beyond '*'.

**Comment by LynnHo** [comment]
@Gulzt I have made a pull request for the configurable banner, you can have a look.
